// Generated by scripts/gen_l10n_dart.py from lib/l10n/*.arb.
// Stands in for the output of `flutter gen-l10n` (output-class: L, per
// l10n.yaml) so the app compiles without running the Flutter SDK in this
// sandbox. Before shipping, run the real generator and diff against this
// file — see README.md "Localization" section.
// ignore_for_file: type=lint

import "package:flutter/material.dart";
import "package:flutter/foundation.dart";
import "app_localizations_en.dart";
import "app_localizations_sw.dart";

/// Base class for DAFTARI's localized strings.
///
/// Swahili is the template language (see l10n.yaml / app_sw.arb) and
/// English is written against it — Rule #10: one language at a time, the
/// two never mix on a single screen.
abstract class L {
  L(this.localeName);

  final String localeName;

  static const LocalizationsDelegate<L> delegate = _LDelegate();

  static const List<Locale> supportedLocales = <Locale>[
    Locale("sw"),
    Locale("en"),
  ];

  static L of(BuildContext context) {
    final l = Localizations.of<L>(context, L);
    assert(l != null, "No L found in context");
    return l!;
  }

  String get appName;
  String get tagline;
  String get actionSave;
  String get actionCancel;
  String get actionUndo;
  String get actionContinue;
  String get actionRetry;
  String get actionDelete;
  String get actionEdit;
  String get actionDone;
  String get actionSkip;
  String get actionGetStarted;
  String get actionAnswer;
  String get actionYes;
  String get actionNotYet;
  String get actionSaveAll;
  String get actionCorrect;
  String get actionVoid;
  String get actionShare;
  String get actionClose;
  String get actionOpen;
  String get actionSync;
  String get actionViewAll;
  String get onboardingLanguageTitle;
  String get onboardingLanguageSubtitle;
  String get onboardingRoleTitle;
  String get onboardingRoleSubtitle;
  String get onboardingRoleMiner;
  String get onboardingRoleMinerDesc;
  String get onboardingRoleSponsor;
  String get onboardingRoleSponsorDesc;
  String get onboardingRoleBuyer;
  String get onboardingRoleBuyerDesc;
  String get onboardingRoleTrader;
  String get onboardingRoleTraderDesc;
  String get onboardingPromisesTitle;
  String get onboardingPromise1;
  String get onboardingPromise2;
  String get onboardingPromise3;
  String get onboardingPromise4;
  String get onboardingPromisesCta;
  String get homeGreeting;
  String get homeTodayLabel;
  String get homeMicHint;
  String get homeCaptureVoice;
  String get homeCaptureType;
  String get homeCaptureQuick;
  String get homeNoEntriesToday;
  String get homeRecentReports;
  String get homeNoRecentReports;
  String get homeYesterday;
  String get chipOre;
  String get chipFuel;
  String get chipMilling;
  String get chipYield;
  String get chipWages;
  String get chipLoan;
  String get chipRepayment;
  String get chipSale;
  String get chipStock;
  String get chipPower;
  String get chipAdvance;
  String get chipRepaymentReceived;
  String get chipPurchase;
  String get navHome;
  String get navWrite;
  String get navQuestions;
  String get navReports;
  String get navMore;
  String get captureListening;
  String get captureHoldToTalk;
  String get captureProcessing;
  String get captureTypedPlaceholder;
  String get captureStop;
  String get captureSwitchToType;
  String get captureSwitchToVoice;
  String get captureQuickTitle;
  String get captureQuickWho;
  String get reviewTitle;
  String get reviewWeightLabel;
  String get reviewAmountLabel;
  String get reviewTotalLabel;
  String get reviewSourceLabel;
  String get reviewConfirm;
  String get reviewLowConfidence;
  String get reviewHeard;
  String get reviewStatusSettled;
  String get reviewStatusConfirmNeeded;
  String get reviewTranscriptLabel;
  String get reviewNoTransactionsFound;
  String get confirmationSaved;
  String get confirmationUndoHint;
  String get confirmationThisWeek;
  String get confirmationLastWeek;
  String get batchTitle;
  String get batchAddAnother;
  String get batchSaveAll;
  String get batchCostBreakdown;
  String get batchTotalCost;
  String get batchYield;
  String get batchCostPerGram;
  String get batchBeforeSelling;
  String get presaleTitle;
  String get presaleYourGold;
  String get presaleBuyerOffers;
  String get presaleYourCost;
  String get presaleProfit;
  String get presaleDecisionIsYours;
  String get inboxTitle;
  String get inboxEmpty;
  String get inboxResolve;
  String inboxGapOreNotMilled(String days);
  String get inboxGapMillingNoYield;
  String inboxGapLoanUnpaid(String counterparty);
  String get dayReportTitle;
  String get dayReportTotalWeight;
  String get dayReportTotalValue;
  String get dayReportEntryCount;
  String get dayReportGapWarning;
  String get dayReportMoneyIn;
  String get dayReportMoneyOut;
  String get dayReportCompleteness;
  String get dayReportYourWords;
  String get dayReportViewOrigin;
  String get originTitle;
  String get originVerbatim;
  String get originPlayAudio;
  String get originEntriesFromThisCapture;
  String get monthReportTitle;
  String get monthReportAverage;
  String get monthReportMoneyIn;
  String get monthReportMoneyOut;
  String get monthReportNet;
  String get monthReportProduction;
  String get monthReportSuppliers;
  String get monthReportBuyers;
  String get monthReportCompleteness;
  String get monthReportShare;
  String get settingsTitle;
  String get settingsLanguage;
  String get settingsRole;
  String get settingsExportData;
  String get settingsAbout;
  String get settingsClearData;
  String get settingsClearDataConfirm;
  String get settingsClearDataWarning;
  String get settingsAboutNotice;
  String get settingsVersion;
  String get unitGrams;
  String get unitKilograms;
  String get currencyLabel;
  String get errorGeneric;
  String get errorNoMicPermission;
  String get errorNoNetwork;
}

class _LDelegate extends LocalizationsDelegate<L> {
  const _LDelegate();

  @override
  bool isSupported(Locale locale) => ["sw", "en"].contains(locale.languageCode);

  @override
  Future<L> load(Locale locale) {
    switch (locale.languageCode) {
      case "en":
        return SynchronousFuture<L>(LEn());
      case "sw":
      default:
        return SynchronousFuture<L>(LSw());
    }
  }

  @override
  bool shouldReload(_LDelegate old) => false;
}
