// Generated by scripts/gen_l10n_dart.py from app_sw.arb.
// This file stands in for the output of `flutter gen-l10n` — see README.md.
// ignore_for_file: type=lint

import "app_localizations.dart";

/// SW strings.
class LSw extends L {
  LSw() : super("sw");

  @override
  String get appName => 'DAFTARI';

  @override
  String get tagline => 'Daftari isiyopotea';

  @override
  String get actionSave => 'Hifadhi';

  @override
  String get actionCancel => 'Ghairi';

  @override
  String get actionUndo => 'Tengua';

  @override
  String get actionContinue => 'Endelea';

  @override
  String get actionRetry => 'Jaribu Tena';

  @override
  String get actionDelete => 'Futa';

  @override
  String get actionEdit => 'Badilisha';

  @override
  String get actionDone => 'Sawa';

  @override
  String get actionSkip => 'Ruka';

  @override
  String get actionGetStarted => 'Anza';

  @override
  String get actionAnswer => 'Jibu';

  @override
  String get actionYes => 'Ndiyo';

  @override
  String get actionNotYet => 'Bado';

  @override
  String get actionSaveAll => 'Hifadhi Zote';

  @override
  String get actionCorrect => 'Sahihisha';

  @override
  String get actionVoid => 'Ondoa';

  @override
  String get actionShare => 'Shiriki';

  @override
  String get actionClose => 'Funga';

  @override
  String get actionOpen => 'Fungua';

  @override
  String get actionSync => 'Sasisha Sasa';

  @override
  String get actionViewAll => 'Ona Zote';

  @override
  String get onboardingLanguageTitle => 'Chagua Lugha';

  @override
  String get onboardingLanguageSubtitle => 'Hakuna akaunti, hakuna ruhusa, hakuna maelezo yanayohitajika.';

  @override
  String get onboardingRoleTitle => 'Wewe ni Nani?';

  @override
  String get onboardingRoleSubtitle => 'Unaweza kubadilisha baadaye.';

  @override
  String get onboardingRoleMiner => 'Mchimbaji';

  @override
  String get onboardingRoleMinerDesc => 'Ninachimba na kuuza dhahabu';

  @override
  String get onboardingRoleSponsor => 'Mzamini';

  @override
  String get onboardingRoleSponsorDesc => 'Ninatoa fedha au vifaa';

  @override
  String get onboardingRoleBuyer => 'Mnunuzi';

  @override
  String get onboardingRoleBuyerDesc => 'Ninanunua dhahabu';

  @override
  String get onboardingRoleTrader => 'Mfanyabiashara Mwingine';

  @override
  String get onboardingRoleTraderDesc => 'Ninanunua, kuuza, na kufuatilia pesa';

  @override
  String get onboardingPromisesTitle => 'Daftari Lako ni Lako';

  @override
  String get onboardingPromise1 => 'Hakuna GPS';

  @override
  String get onboardingPromise2 => 'Hakuna namba ya simu';

  @override
  String get onboardingPromise3 => 'Unaweza kufuta wakati wowote';

  @override
  String get onboardingPromise4 => 'Inafanya kazi bila mtandao';

  @override
  String get onboardingPromisesCta => 'Sawa, Tuanze';

  @override
  String get homeGreeting => 'Habari';

  @override
  String get homeTodayLabel => 'Leo';

  @override
  String get homeYourCostLabel => 'Gharama Yako kwa Gramu';

  @override
  String get homeNoYieldYet => 'Bado hujaandika dhahabu kwenye batch hii';

  @override
  String get homeCostNote => 'Kutoka gharama zako halisi za ununuzi na uchakataji — kamwe si bei ya soko.';

  @override
  String get homeMicHint => 'Bonyeza na Ongea';

  @override
  String get homeBatchSummary => 'Kundi la Sasa';

  @override
  String get homeCaptureVoice => 'Sema';

  @override
  String get homeCaptureType => 'Andika';

  @override
  String get homeCaptureQuick => 'Haraka';

  @override
  String get homeNoEntriesToday => 'Bado hakuna kumbukumbu leo';

  @override
  String get chipOre => 'Mawe';

  @override
  String get chipFuel => 'Mafuta';

  @override
  String get chipMilling => 'Kusaga';

  @override
  String get chipYield => 'Dhahabu';

  @override
  String get chipWages => 'Vibarua';

  @override
  String get chipLoan => 'Mkopo';

  @override
  String get chipRepayment => 'Marejesho';

  @override
  String get chipSale => 'Mauzo';

  @override
  String get chipStock => 'Bidhaa';

  @override
  String get chipPower => 'Umeme';

  @override
  String get chipAdvance => 'Mkopo Ulotoa';

  @override
  String get chipRepaymentReceived => 'Marejesho Uliyopokea';

  @override
  String get chipPurchase => 'Ununuzi';

  @override
  String get navHome => 'Nyumbani';

  @override
  String get navWrite => 'Andika';

  @override
  String get navQuestions => 'Maswali';

  @override
  String get navReports => 'Ripoti';

  @override
  String get navMore => 'Zaidi';

  @override
  String get captureListening => 'Ninasikiliza...';

  @override
  String get captureHoldToTalk => 'Bonyeza mara moja kuanza, tena kusimamisha';

  @override
  String get captureProcessing => 'Ninachakata...';

  @override
  String get captureTypedPlaceholder => 'Andika kila ulichofanya. Mfumo utapanga.';

  @override
  String get captureStop => 'Simamisha';

  @override
  String get captureSwitchToType => 'Andika badala yake';

  @override
  String get captureSwitchToVoice => 'Sema badala yake';

  @override
  String get captureQuickTitle => 'Kumbukumbu ya Haraka';

  @override
  String get captureQuickWho => 'Nani? (hiari)';

  @override
  String get reviewTitle => 'Kagua Kumbukumbu';

  @override
  String get reviewWeightLabel => 'Uzito (gramu)';

  @override
  String get reviewAmountLabel => 'Kiasi';

  @override
  String get reviewTotalLabel => 'Jumla';

  @override
  String get reviewSourceLabel => 'Chanzo';

  @override
  String get reviewConfirm => 'Thibitisha na Hifadhi';

  @override
  String get reviewLowConfidence => 'Sikuwa na uhakika. Mguso mmoja unatatua.';

  @override
  String get reviewHeard => 'Nimesikia';

  @override
  String get reviewStatusSettled => 'Imekamilika';

  @override
  String get reviewStatusConfirmNeeded => 'Thibitisha';

  @override
  String get reviewTranscriptLabel => 'Ulichosema';

  @override
  String get reviewNoTransactionsFound => 'Sikupata muamala popote. Jaribu tena, au andika badala yake.';

  @override
  String get confirmationSaved => 'Nimeandika';

  @override
  String get confirmationUndoHint => 'Unaweza kutengua ndani ya sekunde chache';

  @override
  String get confirmationThisWeek => 'Wiki hii';

  @override
  String get confirmationLastWeek => 'Wiki iliyopita';

  @override
  String get batchTitle => 'Batch Hii';

  @override
  String get batchAddAnother => 'Ongeza Nyingine';

  @override
  String get batchSaveAll => 'Hifadhi Zote';

  @override
  String get batchCostBreakdown => 'Gharama';

  @override
  String get batchTotalCost => 'Jumla';

  @override
  String get batchYield => 'Dhahabu';

  @override
  String get batchCostPerGram => 'Kwa Gramu';

  @override
  String get batchBeforeSelling => 'Kabla Hujauza';

  @override
  String get presaleTitle => 'Kabla Hujauza';

  @override
  String get presaleYourGold => 'Dhahabu Yako';

  @override
  String get presaleBuyerOffers => 'Mnunuzi Anatoa';

  @override
  String get presaleYourCost => 'Gharama Yako';

  @override
  String get presaleProfit => 'Faida Ukiuza Sasa';

  @override
  String get presaleDecisionIsYours => 'Uamuzi ni wako.';

  @override
  String get inboxTitle => 'Maswali';

  @override
  String get inboxEmpty => 'Hakuna maswali kwa sasa';

  @override
  String get inboxResolve => 'Jibu';

  @override
  String inboxGapOreNotMilled(String days) => 'Mawe yaliyonunuliwa siku $days zilizopita — umeshayasaga?';

  @override
  String get inboxGapMillingNoYield => 'Umesaga lakini hujaandika mavuno — ulipata gramu ngapi?';

  @override
  String inboxGapLoanUnpaid(String counterparty) => 'Mkopo kwa $counterparty haujarejeshwa kwa zaidi ya miezi miwili — bado unadaiwa?';

  @override
  String get dayReportTitle => 'Siku ya Leo';

  @override
  String get dayReportTotalWeight => 'Uzito wa Jumla';

  @override
  String get dayReportTotalValue => 'Thamani ya Jumla';

  @override
  String get dayReportEntryCount => 'Idadi ya Kumbukumbu';

  @override
  String get dayReportGapWarning => 'Baadhi ya kumbukumbu bado hazijakamilika';

  @override
  String get dayReportMoneyIn => 'Imeingia';

  @override
  String get dayReportMoneyOut => 'Imetoka';

  @override
  String get dayReportCompleteness => 'Ukamilifu';

  @override
  String get dayReportYourWords => 'Maelezo Yako';

  @override
  String get dayReportViewOrigin => 'Ona sentensi halisi';

  @override
  String get originTitle => 'Chanzo';

  @override
  String get originVerbatim => 'Ulichosema, kama kilivyo';

  @override
  String get originPlayAudio => 'Cheza Sauti';

  @override
  String get originEntriesFromThisCapture => 'Kumbukumbu za Sauti Hii';

  @override
  String get monthReportTitle => 'Ripoti ya Mwezi';

  @override
  String get monthReportAverage => 'Wastani wa Bei';

  @override
  String get monthReportMoneyIn => 'Imeingia';

  @override
  String get monthReportMoneyOut => 'Imetoka';

  @override
  String get monthReportNet => 'Faida';

  @override
  String get monthReportProduction => 'Uzalishaji';

  @override
  String get monthReportSuppliers => 'Wauzaji wa Mawe';

  @override
  String get monthReportBuyers => 'Wanunuzi';

  @override
  String get monthReportCompleteness => 'Ukamilifu';

  @override
  String get monthReportShare => 'Shiriki Ripoti';

  @override
  String get settingsTitle => 'Mipangilio';

  @override
  String get settingsLanguage => 'Lugha';

  @override
  String get settingsRole => 'Nafasi';

  @override
  String get settingsExportData => 'Hamisha Data';

  @override
  String get settingsAbout => 'Kuhusu';

  @override
  String get settingsClearData => 'Futa Data Yote';

  @override
  String get settingsClearDataConfirm => 'Hili haliwezi kutenguliwa. Futa yote?';

  @override
  String get settingsClearDataWarning => 'Kila kumbukumbu na sauti kwenye simu hii itafutwa kabisa.';

  @override
  String get settingsAboutNotice => 'Programu hii haitoi ushauri wa kuuza wala bei ya soko. Inaonyesha hesabu ya gharama na faida yako halisi tu.';

  @override
  String get settingsVersion => 'Toleo';

  @override
  String get unitGrams => 'gramu';

  @override
  String get unitKilograms => 'kilo';

  @override
  String get currencyLabel => 'Shilingi';

  @override
  String get errorGeneric => 'Hitilafu imetokea. Data yako iko salama kwenye simu.';

  @override
  String get errorNoMicPermission => 'Ruhusa ya kipaza sauti inahitajika kurekodi.';

  @override
  String get errorNoNetwork => 'Hakuna mtandao. Imehifadhiwa na itasawazishwa baadaye.';

}
