// Generated by scripts/gen_l10n_dart.py from app_en.arb.
// This file stands in for the output of `flutter gen-l10n` — see README.md.
// ignore_for_file: type=lint

import "app_localizations.dart";

/// EN strings.
class LEn extends L {
  LEn() : super("en");

  @override
  String get appName => 'DAFTARI';

  @override
  String get tagline => 'A ledger that cannot be lost';

  @override
  String get actionSave => 'Save';

  @override
  String get actionCancel => 'Cancel';

  @override
  String get actionUndo => 'Undo';

  @override
  String get actionContinue => 'Continue';

  @override
  String get actionRetry => 'Retry';

  @override
  String get actionDelete => 'Delete';

  @override
  String get actionEdit => 'Edit';

  @override
  String get actionDone => 'Done';

  @override
  String get actionSkip => 'Skip';

  @override
  String get actionGetStarted => 'Get Started';

  @override
  String get actionAnswer => 'Answer';

  @override
  String get actionYes => 'Yes';

  @override
  String get actionNotYet => 'Not yet';

  @override
  String get actionSaveAll => 'Save all';

  @override
  String get actionCorrect => 'Correct';

  @override
  String get actionVoid => 'Remove';

  @override
  String get actionShare => 'Share';

  @override
  String get actionClose => 'Close';

  @override
  String get actionOpen => 'Open';

  @override
  String get actionSync => 'Sync now';

  @override
  String get actionViewAll => 'View all';

  @override
  String get onboardingLanguageTitle => 'Choose your language';

  @override
  String get onboardingLanguageSubtitle => 'No account, no permissions, no explanation needed.';

  @override
  String get onboardingRoleTitle => 'Who are you?';

  @override
  String get onboardingRoleSubtitle => 'You can change this later.';

  @override
  String get onboardingRoleMiner => 'Miner';

  @override
  String get onboardingRoleMinerDesc => 'I dig and sell gold';

  @override
  String get onboardingRoleSponsor => 'Sponsor';

  @override
  String get onboardingRoleSponsorDesc => 'I provide money or equipment';

  @override
  String get onboardingRoleBuyer => 'Buyer';

  @override
  String get onboardingRoleBuyerDesc => 'I buy gold';

  @override
  String get onboardingRoleTrader => 'Other trader';

  @override
  String get onboardingRoleTraderDesc => 'I buy, sell, and keep track of money';

  @override
  String get onboardingPromisesTitle => 'Your ledger is yours';

  @override
  String get onboardingPromise1 => 'No GPS location tracking';

  @override
  String get onboardingPromise2 => 'No phone number required';

  @override
  String get onboardingPromise3 => 'You can delete everything, anytime';

  @override
  String get onboardingPromise4 => 'Works with no network, always';

  @override
  String get onboardingPromisesCta => 'Okay, let\'s start';

  @override
  String get homeGreeting => 'Hello';

  @override
  String get homeTodayLabel => 'Today';

  @override
  String get homeMicHint => 'Press and speak';

  @override
  String get homeCaptureVoice => 'Speak';

  @override
  String get homeCaptureType => 'Type';

  @override
  String get homeCaptureQuick => 'Quick';

  @override
  String get homeNoEntriesToday => 'No entries yet today';

  @override
  String get homeRecentReports => 'Recent reports';

  @override
  String get homeNoRecentReports => 'Your reports will appear here once you record something';

  @override
  String get homeYesterday => 'Yesterday';

  @override
  String get chipOre => 'Ore';

  @override
  String get chipFuel => 'Fuel';

  @override
  String get chipMilling => 'Milling';

  @override
  String get chipYield => 'Yield';

  @override
  String get chipWages => 'Wages';

  @override
  String get chipLoan => 'Loan given';

  @override
  String get chipRepayment => 'Repayment';

  @override
  String get chipSale => 'Sale';

  @override
  String get chipStock => 'Stock';

  @override
  String get chipPower => 'Power';

  @override
  String get chipAdvance => 'Advance given';

  @override
  String get chipRepaymentReceived => 'Repayment received';

  @override
  String get chipPurchase => 'Purchase';

  @override
  String get navHome => 'Home';

  @override
  String get navWrite => 'Write';

  @override
  String get navQuestions => 'Questions';

  @override
  String get navReports => 'Reports';

  @override
  String get navMore => 'More';

  @override
  String get captureListening => 'Listening…';

  @override
  String get captureHoldToTalk => 'Press once to start, again to stop';

  @override
  String get captureProcessing => 'Working it out…';

  @override
  String get captureTypedPlaceholder => 'Write down everything you did. The system will arrange it.';

  @override
  String get captureStop => 'Stop';

  @override
  String get captureSwitchToType => 'Type instead';

  @override
  String get captureSwitchToVoice => 'Speak instead';

  @override
  String get captureQuickTitle => 'Quick entry';

  @override
  String get captureQuickWho => 'Who? (optional)';

  @override
  String get reviewTitle => 'Review';

  @override
  String get reviewWeightLabel => 'Weight (grams)';

  @override
  String get reviewAmountLabel => 'Amount';

  @override
  String get reviewTotalLabel => 'Total';

  @override
  String get reviewSourceLabel => 'Source';

  @override
  String get reviewConfirm => 'Confirm and save';

  @override
  String get reviewLowConfidence => 'Not sure about this one. A tap resolves it.';

  @override
  String get reviewHeard => 'Heard';

  @override
  String get reviewStatusSettled => 'Settled';

  @override
  String get reviewStatusConfirmNeeded => 'Confirm';

  @override
  String get reviewTranscriptLabel => 'What you said';

  @override
  String get reviewNoTransactionsFound => 'I could not find a transaction in that. Try again, or type it instead.';

  @override
  String get confirmationSaved => 'Saved';

  @override
  String get confirmationUndoHint => 'Undo is available for a few seconds';

  @override
  String get confirmationThisWeek => 'This week';

  @override
  String get confirmationLastWeek => 'Last week';

  @override
  String get batchTitle => 'This batch';

  @override
  String get batchAddAnother => 'Add another';

  @override
  String get batchSaveAll => 'Save all';

  @override
  String get batchCostBreakdown => 'Costs';

  @override
  String get batchTotalCost => 'Total cost';

  @override
  String get batchYield => 'Output';

  @override
  String get batchCostPerGram => 'Cost per unit';

  @override
  String get batchBeforeSelling => 'Before you sell';

  @override
  String get presaleTitle => 'Before you sell';

  @override
  String get presaleYourGold => 'Your output';

  @override
  String get presaleBuyerOffers => 'Buyer offers';

  @override
  String get presaleYourCost => 'This batch cost you';

  @override
  String get presaleProfit => 'Profit at this offer';

  @override
  String get presaleDecisionIsYours => 'The decision is yours.';

  @override
  String get inboxTitle => 'Questions';

  @override
  String get inboxEmpty => 'No questions right now';

  @override
  String get inboxResolve => 'Answer';

  @override
  String inboxGapOreNotMilled(String days) => 'Ore bought $days days ago — has it been milled yet?';

  @override
  String get inboxGapMillingNoYield => 'A mill run was recorded with no yield — how much gold came out?';

  @override
  String inboxGapLoanUnpaid(String counterparty) => 'A loan to $counterparty has had no repayment for over two months — still outstanding?';

  @override
  String get dayReportTitle => 'Today';

  @override
  String get dayReportTotalWeight => 'Total weight';

  @override
  String get dayReportTotalValue => 'Total value';

  @override
  String get dayReportEntryCount => 'Entries';

  @override
  String get dayReportGapWarning => 'Some entries are still incomplete';

  @override
  String get dayReportMoneyIn => 'Money in';

  @override
  String get dayReportMoneyOut => 'Money out';

  @override
  String get dayReportCompleteness => 'Completeness';

  @override
  String get dayReportYourWords => 'Your own words';

  @override
  String get dayReportViewOrigin => 'See the original sentence';

  @override
  String get originTitle => 'Origin';

  @override
  String get originVerbatim => 'What was said, exactly';

  @override
  String get originPlayAudio => 'Play recording';

  @override
  String get originEntriesFromThisCapture => 'Entries from this recording';

  @override
  String get monthReportTitle => 'Month report';

  @override
  String get monthReportAverage => 'Average price received';

  @override
  String get monthReportMoneyIn => 'Money in';

  @override
  String get monthReportMoneyOut => 'Money out';

  @override
  String get monthReportNet => 'Net';

  @override
  String get monthReportProduction => 'Production';

  @override
  String get monthReportSuppliers => 'Ore suppliers';

  @override
  String get monthReportBuyers => 'Buyers';

  @override
  String get monthReportCompleteness => 'Completeness';

  @override
  String get monthReportShare => 'Share report';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get settingsLanguage => 'Language';

  @override
  String get settingsRole => 'Role';

  @override
  String get settingsExportData => 'Export data';

  @override
  String get settingsAbout => 'About';

  @override
  String get settingsClearData => 'Delete all data';

  @override
  String get settingsClearDataConfirm => 'This cannot be undone. Delete everything?';

  @override
  String get settingsClearDataWarning => 'Every capture and entry on this device will be permanently removed.';

  @override
  String get settingsAboutNotice => 'This app gives no advice on whether to sell and claims no market price. It shows your own cost and profit arithmetic only.';

  @override
  String get settingsVersion => 'Version';

  @override
  String get unitGrams => 'units';

  @override
  String get unitKilograms => 'kilograms';

  @override
  String get currencyLabel => 'Shillings';

  @override
  String get errorGeneric => 'Something went wrong. Your data is safe on this device.';

  @override
  String get errorNoMicPermission => 'Microphone access is needed to record.';

  @override
  String get errorNoNetwork => 'No network. Saved and will sync later.';

}
