include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/l10n/app_localizations*.dart"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    require_trailing_commas: true
    unawaited_futures: true
    use_super_parameters: true
    sort_constructors_first: true
