"""
Hand-writes the Dart localization classes that `flutter gen-l10n` would
normally generate from the ARB files, since the Flutter SDK is not available
in this build environment. Structure mirrors the real generator's output
closely enough that running the real tool later (see README.md) is a
drop-in replacement, not a rewrite.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "flutter" / "daftari"
L10N_DIR = ROOT / "lib" / "l10n"

def load(locale: str) -> dict:
    data = json.loads((L10N_DIR / f"app_{locale}.arb").read_text(encoding="utf-8"))
    return {k: v for k, v in data.items() if not k.startswith("@")}

PLACEHOLDER_RE = re.compile(r"\{(\w+)(?:,\s*plural,.*)?\}")

def placeholders(value: str) -> list[str]:
    names = []
    for m in re.finditer(r"\{(\w+)", value):
        name = m.group(1)
        if name not in names:
            names.append(name)
    return names

def dart_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")

def render_plural(key: str, en_value: str) -> str | None:
    """Handles the one ICU-plural string by hand; returns a Dart method body."""
    m = re.match(r"^\{(\w+), plural, one\{(.*?)\} other\{(.*?)\}\}$", en_value)
    if not m:
        return None
    var, one, other = m.groups()
    return var, one, other

def build_locale_file(locale: str, class_name: str, strings: dict) -> str:
    lines = []
    lines.append(f"// Generated by scripts/gen_l10n_dart.py from app_{locale}.arb.")
    lines.append("// This file stands in for the output of `flutter gen-l10n` — see README.md.")
    lines.append("// ignore_for_file: type=lint")
    lines.append("")
    lines.append('import "app_localizations.dart";')
    lines.append("")
    lines.append(f"/// {locale.upper()} strings.")
    lines.append(f"class {class_name} extends L {{")
    lines.append(f'  {class_name}() : super("{locale}");')
    lines.append("")
    for key, value in strings.items():
        plural = render_plural(key, value) if "plural" in value else None
        ph = placeholders(value)
        if plural:
            var, one, other = plural
            lines.append("  @override")
            lines.append(f"  String {key}(int {var}) {{")
            lines.append(f"    if ({var} == 1) return '{dart_escape(one)}';")
            other_dart = other.replace("{" + var + "}", "$" + var)
            lines.append(f"    return '{dart_escape(other_dart)}';")
            lines.append("  }")
        elif ph:
            args = ", ".join(f"String {p}" for p in ph)
            body = value
            for p in ph:
                body = body.replace("{" + p + "}", "$" + p)
            lines.append("  @override")
            lines.append(f"  String {key}({args}) => '{dart_escape(body)}';")
        else:
            lines.append("  @override")
            lines.append(f"  String get {key} => '{dart_escape(value)}';")
        lines.append("")
    lines.append("}")
    return "\n".join(lines)

def build_base_file(en: dict) -> str:
    lines = []
    lines.append("// Generated by scripts/gen_l10n_dart.py from lib/l10n/*.arb.")
    lines.append("// Stands in for the output of `flutter gen-l10n` (output-class: L, per")
    lines.append("// l10n.yaml) so the app compiles without running the Flutter SDK in this")
    lines.append("// sandbox. Before shipping, run the real generator and diff against this")
    lines.append("// file — see README.md \"Localization\" section.")
    lines.append("// ignore_for_file: type=lint")
    lines.append("")
    lines.append('import "package:flutter/material.dart";')
    lines.append('import "package:flutter/foundation.dart";')
    lines.append('import "app_localizations_en.dart";')
    lines.append('import "app_localizations_sw.dart";')
    lines.append("")
    lines.append("/// Base class for DAFTARI's localized strings.")
    lines.append("///")
    lines.append("/// Swahili is the template language (see l10n.yaml / app_sw.arb) and")
    lines.append("/// English is written against it — Rule #10: one language at a time, the")
    lines.append("/// two never mix on a single screen.")
    lines.append("abstract class L {")
    lines.append("  L(this.localeName);")
    lines.append("")
    lines.append("  final String localeName;")
    lines.append("")
    lines.append("  static const LocalizationsDelegate<L> delegate = _LDelegate();")
    lines.append("")
    lines.append("  static const List<Locale> supportedLocales = <Locale>[")
    lines.append('    Locale("sw"),')
    lines.append('    Locale("en"),')
    lines.append("  ];")
    lines.append("")
    lines.append("  static L of(BuildContext context) {")
    lines.append("    final l = Localizations.of<L>(context, L);")
    lines.append("    assert(l != null, \"No L found in context\");")
    lines.append("    return l!;")
    lines.append("  }")
    lines.append("")
    for key, value in en.items():
        plural = render_plural(key, value) if "plural" in value else None
        ph = placeholders(value)
        if plural:
            var = plural[0]
            lines.append(f"  String {key}(int {var});")
        elif ph:
            args = ", ".join(f"String {p}" for p in ph)
            lines.append(f"  String {key}({args});")
        else:
            lines.append(f"  String get {key};")
    lines.append("}")
    lines.append("")
    lines.append("class _LDelegate extends LocalizationsDelegate<L> {")
    lines.append("  const _LDelegate();")
    lines.append("")
    lines.append("  @override")
    lines.append('  bool isSupported(Locale locale) => ["sw", "en"].contains(locale.languageCode);')
    lines.append("")
    lines.append("  @override")
    lines.append("  Future<L> load(Locale locale) {")
    lines.append('    switch (locale.languageCode) {')
    lines.append('      case "en":')
    lines.append("        return SynchronousFuture<L>(LEn());")
    lines.append('      case "sw":')
    lines.append("      default:")
    lines.append("        return SynchronousFuture<L>(LSw());")
    lines.append("    }")
    lines.append("  }")
    lines.append("")
    lines.append("  @override")
    lines.append("  bool shouldReload(_LDelegate old) => false;")
    lines.append("}")
    return "\n".join(lines)

if __name__ == "__main__":
    sw = load("sw")
    en = load("en")
    assert sw.keys() == en.keys(), "sw/en key sets diverged"

    (L10N_DIR / "app_localizations.dart").write_text(build_base_file(en) + "\n", encoding="utf-8")
    (L10N_DIR / "app_localizations_en.dart").write_text(build_locale_file("en", "LEn", en) + "\n", encoding="utf-8")
    (L10N_DIR / "app_localizations_sw.dart").write_text(build_locale_file("sw", "LSw", sw) + "\n", encoding="utf-8")
    print("Generated app_localizations.dart, app_localizations_en.dart, app_localizations_sw.dart")
